@startuml FreemanNetwork
skinparam linetype ortho
skinparam rectangle {
  BackgroundColor #f9fafb
  BorderColor #555
  RoundCorner 8
}

title SYS-350 Network Diagram

rectangle "Freeman Network\n192.168.3.0/24" as FREEMAN {
  rectangle "Gateway\n192.168.3.250" as GW
  rectangle "Cisco 3750 SW" as SW
  rectangle "Firewall (Freeman iface)\n192.168.3.36" as LINK_FREEMAN
  rectangle "Freeman Workstations\n192.168.3.100 – .120" as WS
    rectangle "SuperMicro" as SERVER {
        rectangle "SuperMicro ipmi\n192.168.3.176" as IPMI
        rectangle "ESXI\n192.168.3.226" as ESXI
    }
}

rectangle "350-Internal Network\n10.0.17.0/24" as LAN_INTERNAL {
  rectangle "Firewall (Internal iface)\n10.0.17.2" as LINK_INTERNAL
  rectangle "dc1\n10.0.17.4" as DC1
  rectangle "vCenter\n10.0.17.3" as vCenter
}

rectangle "DMZ Network\n10.0.18.0/24" as DMZ_INTERNAL {
  rectangle "Firewall (DMZ iface)\n10.0.18.2" as LINK_DMZ
  rectangle "Web01\n10.0.18.10" as web01
}

rectangle "MGMT Network\n10.0.19.0/24" as MGMT_INTERNAL {
  rectangle "Firewall (MGMT iface)\n10.0.19.2" as LINK_MGMT
  rectangle "Mgmt01\n10.0.19.100" as mgmt
  rectangle "backup01\n10.0.19.10"as backup01
}

  

' --- Connections ---
SW -[dashed]-> LINK_FREEMAN
SW -[dashed]-> IPMI
GW -[dashed]-> SW
GW -[dashed]-> WS
IPMI -[dashed]-> ESXI

LINK_FREEMAN -[bold]-> LINK_INTERNAL : routed link
LINK_FREEMAN -[bold]-> LINK_DMZ : routed link
LINK_FREEMAN -[bold]-> LINK_MGMT : routed link

LINK_INTERNAL -[dashed]-> DC1
LINK_INTERNAL -[dashed]-> vCenter

LINK_DMZ -[dashed]-> web01

LINK_MGMT -[dashed]-> mgmt
LINK_MGMT -[dashed]-> backup01




@enduml
