
network:
  version: 2
  ethernets:
       ens18:
         dhcp4: false
         addresses: [172.16.50.5/24]
         nameservers:
             addresses: [172.16.50.2]
         routes:
             - to: default
               via: 172.16.50.2

